export const OPEN_EDIT_PROFILE = "OPEN_EDIT_PROFILE";
export const CLOSE_EDIT_PROFILE = "CLOSE_EDIT_PROFILE";

export const OPEN_EVENT_DETAILS = "OPEN_EVENT_DETAILS";
export const CLOSE_EVENT_DETAILS = "CLOSE_EVENT_DETAILS";

export const OPEN_CHAT = "OPEN_CHAT";
export const CLOSE_CHAT = "CLOSE_CHAT";
